---

- name: Update packages on CentOS and Ubuntu
  hosts: all
  become: true
  tags: always
  pre_tasks:
  
  - name: Update Packages on CentOS
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Update Packages on Ubuntu
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- name: Install apache on Webservers
  hosts: web_server
  become: true
  tags: playWebserver
  tasks:
  
  - name: Install apache on CentOS
    tags: CentOS,httpd,apache
    dnf:
      name: 
        - httpd
        - php 
      state: latest 
    when: ansible_distribution == "CentOS"

  - name: Install apache on Ubuntu
    tags: Ubuntu,apache2,apache
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Enable httpd service (CentOS)
    tags: httpd,CentOS,apache
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: Enable port 80 for httpd service (CentOS)
    tags: httpd,apache, CentOS
    firewalld:
      port: 80/tcp
      state: enabled
      immediate: true
    when: ansible_distribution == "CentOS"

  - name: Copy default html to web servers
    tags: httpd,apache,apache2
    copy: 
      src: default-site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    
- name: Configuration change for CentOS httpd
  hosts: web_server
  become: true
  tasks:
  - name: Change admin email address (CentOS)
    tags: httpd,CentOS,apache
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin kripalparsekar.it@gmail.com
    when: ansible_distribution == "CentOS"
    register: httpd_change

  - name: Restart CentOS server after config change
    tags: httpd,CentOS,apache
    service:
      name: httpd
      state: restarted
    when: httpd_change.changed

- name: Install MariaDB on Database servers
  hosts: db_server
  become: true
  tags: playDB
  tasks:

    - name: Install MariaDB on CentOS
      tags: CentOS,mariadb,db  
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Install MariaDB on Ubuntu
      tags: Ubuntu,mariadb,db
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"


  
